pipeline:
  name: brew
  identifier: brew
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: brew
        build: <+input>
  stages:
    - stage:
        name: docker
        identifier: docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Fetch origin-master from Git
                  identifier: Fetch_originmaster_from_Git
                  spec:
                    shell: Sh
                    command: git fetch origin master
              - step:
                  type: Run
                  name: Install Docker
                  identifier: Create_Docker_Image
                  spec:
                    shell: Sh
                    command: sudo apt-get install docker-ce docker-ce-cli containerd.io
              - step:
                  type: Run
                  name: Build docker image
                  identifier: Build_docker_image
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: alpine
                    shell: Sh
                    command: |-
                      brew_version="git describe --tags --dirty --abbrev=7"
                      echo "Building for Homebrew ${brew_version}"
                      docker build -t brew \
