pipeline:
  name: brew
  identifier: brew
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: brew
        build: <+input>
  stages:
    - stage:
        name: docker
        identifier: docker
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Fetch origin-master from Git
                  identifier: Fetch_originmaster_from_Git
                  spec:
                    shell: Sh
                    command: git fetch origin master
              - step:
                  type: Run
                  name: Build docker image
                  identifier: Build_docker_image
                  spec:
                    shell: Sh
                    command: |2
                                brew_version="$(git describe --tags --dirty --abbrev=7)"
                                echo "Building for Homebrew ${brew_version}"
                                docker build -t brew \
                                     --build-arg=version=${{matrix.version}} \
                                     --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
                                     --label org.opencontainers.image.url="https://brew.sh" \
                                     --label org.opencontainers.image.documentation="https://docs.brew.sh" \
                                     --label org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}" \
                                     --label org.opencontainers.image.version="${brew_version}" \
                                     --label org.opencontainers.image.revision="${GITHUB_SHA}" \
                                     --label org.opencontainers.image.vendor="${GITHUB_REPOSITORY_OWNER}" \
                                     --label org.opencontainers.image.licenses="BSD-2-Clause" \
                                     .
